mqtt_host: localhost

scales:
  0x00F202D0:
    scale_name: mio_mate
    tare: 9024900
    crate_weight: 12.81
    tolerance: 0.5
    kilogram: -20800
  0x00499A78:
    scale_name: jever
    tare: 9004050
    crate_weight: 20.40
    tolerance: 0.5
    kilogram: -20800
