mqtt_host: localhost

scales:
  0x0049971d:
    scale_name: apfelschorle
    tare: 8153535
    kilogram: -23350
    crate_weight: 11.27
    tolerance: 0.5
  0x003cc863:
    scale_name: mineralwasser
    tare: 8434000
    kilogram: -23940
    crate_weight: 14.34
    tolerance: 0.5
  0x003cc787:
    scale_name: radler
    tare: 8474595
    kilogram: -22870
    crate_weight: 11.23
    tolerance: 0.5
